// Meta Ads module schema. Kept in its own file so the module can be enabled or
// removed independently of the core dashboard tables. Every statement is
// idempotent (CREATE ... IF NOT EXISTS) and runs on both SQLite and Postgres.
//
// Conventions shared with the rest of the schema:
// - internal integer ids, Meta's own ids kept verbatim in TEXT columns
// - dates are 'YYYY-MM-DD' TEXT (the ad account's reporting day)
// - hierarchy tables reference their parents by Meta id, so a sync can upsert
//   children without a lookup round-trip per row

function dialect(db) {
  const pg = db.type === 'postgres';
  return {
    id: pg ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT',
    ts: pg ? 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP' : "TEXT NOT NULL DEFAULT (datetime('now'))",
    num: pg ? 'DOUBLE PRECISION' : 'REAL',
    big: pg ? 'BIGINT' : 'INTEGER',
  };
}

function metaAdsStatements(db) {
  const { id, ts, num, big } = dialect(db);
  return [
    `CREATE TABLE IF NOT EXISTS meta_connections (
      id ${id},
      name TEXT NOT NULL,
      meta_user_id TEXT,
      meta_user_name TEXT,
      auth_type TEXT NOT NULL DEFAULT 'token',
      access_token_encrypted TEXT NOT NULL,
      token_expires_at TEXT,
      scopes TEXT,
      status TEXT NOT NULL DEFAULT 'connected',
      last_error TEXT,
      last_sync_at TEXT,
      last_success_at TEXT,
      created_by INTEGER,
      created_at ${ts},
      updated_at ${ts}
    )`,

    `CREATE TABLE IF NOT EXISTS meta_ad_accounts (
      id ${id},
      connection_id INTEGER,
      meta_ad_account_id TEXT NOT NULL UNIQUE,
      name TEXT,
      currency TEXT,
      timezone_name TEXT,
      account_status INTEGER,
      spend_cap ${num},
      amount_spent ${num},
      business_id TEXT,
      business_name TEXT,
      enabled INTEGER NOT NULL DEFAULT 1,
      last_insights_date TEXT,
      last_sync_at TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_ad_accounts_connection ON meta_ad_accounts(connection_id)',

    `CREATE TABLE IF NOT EXISTS meta_pages (
      id ${id},
      connection_id INTEGER,
      meta_page_id TEXT NOT NULL UNIQUE,
      name TEXT,
      category TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,

    `CREATE TABLE IF NOT EXISTS meta_campaigns (
      id ${id},
      ad_account_id TEXT NOT NULL,
      meta_campaign_id TEXT NOT NULL UNIQUE,
      name TEXT,
      objective TEXT,
      status TEXT,
      effective_status TEXT,
      buying_type TEXT,
      daily_budget ${num},
      lifetime_budget ${num},
      created_time TEXT,
      updated_time TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_campaigns_account ON meta_campaigns(ad_account_id)',

    `CREATE TABLE IF NOT EXISTS meta_adsets (
      id ${id},
      ad_account_id TEXT NOT NULL,
      campaign_id TEXT NOT NULL,
      meta_adset_id TEXT NOT NULL UNIQUE,
      name TEXT,
      status TEXT,
      effective_status TEXT,
      daily_budget ${num},
      lifetime_budget ${num},
      optimization_goal TEXT,
      billing_event TEXT,
      targeting_json TEXT,
      created_time TEXT,
      updated_time TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_adsets_account ON meta_adsets(ad_account_id)',
    'CREATE INDEX IF NOT EXISTS idx_meta_adsets_campaign ON meta_adsets(campaign_id)',

    `CREATE TABLE IF NOT EXISTS meta_ads (
      id ${id},
      ad_account_id TEXT NOT NULL,
      campaign_id TEXT NOT NULL,
      adset_id TEXT NOT NULL,
      meta_ad_id TEXT NOT NULL UNIQUE,
      name TEXT,
      status TEXT,
      effective_status TEXT,
      creative_id TEXT,
      page_id TEXT,
      thumbnail_url TEXT,
      created_time TEXT,
      updated_time TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_ads_account ON meta_ads(ad_account_id)',
    'CREATE INDEX IF NOT EXISTS idx_meta_ads_campaign ON meta_ads(campaign_id)',
    'CREATE INDEX IF NOT EXISTS idx_meta_ads_adset ON meta_ads(adset_id)',
    'CREATE INDEX IF NOT EXISTS idx_meta_ads_page ON meta_ads(page_id)',

    // One row per ad per reporting day. The unique (ad_id, date) key is what
    // makes re-syncing a day an idempotent overwrite instead of a duplicate.
    // ctr/cpc/cpm/frequency are Meta's per-row values kept for reference;
    // every report recomputes them from the summed counters instead, because
    // ratios cannot be averaged across rows.
    `CREATE TABLE IF NOT EXISTS meta_insights_daily (
      id ${id},
      date TEXT NOT NULL,
      ad_account_id TEXT NOT NULL,
      page_id TEXT,
      campaign_id TEXT,
      adset_id TEXT,
      ad_id TEXT NOT NULL,
      spend ${num} NOT NULL DEFAULT 0,
      impressions ${big} NOT NULL DEFAULT 0,
      reach ${big} NOT NULL DEFAULT 0,
      clicks ${big} NOT NULL DEFAULT 0,
      link_clicks ${big} NOT NULL DEFAULT 0,
      ctr ${num},
      cpc ${num},
      cpm ${num},
      frequency ${num},
      purchases ${num} NOT NULL DEFAULT 0,
      purchase_value ${num} NOT NULL DEFAULT 0,
      leads ${num} NOT NULL DEFAULT 0,
      messages ${num} NOT NULL DEFAULT 0,
      actions_json TEXT,
      created_at ${ts},
      updated_at ${ts}
    )`,
    'CREATE UNIQUE INDEX IF NOT EXISTS idx_meta_insights_ad_date ON meta_insights_daily(ad_id, date)',
    'CREATE INDEX IF NOT EXISTS idx_meta_insights_date ON meta_insights_daily(date)',
    'CREATE INDEX IF NOT EXISTS idx_meta_insights_account_date ON meta_insights_daily(ad_account_id, date)',
    'CREATE INDEX IF NOT EXISTS idx_meta_insights_campaign_date ON meta_insights_daily(campaign_id, date)',
    'CREATE INDEX IF NOT EXISTS idx_meta_insights_adset_date ON meta_insights_daily(adset_id, date)',
    'CREATE INDEX IF NOT EXISTS idx_meta_insights_page_date ON meta_insights_daily(page_id, date)',

    `CREATE TABLE IF NOT EXISTS meta_sync_logs (
      id ${id},
      connection_id INTEGER,
      ad_account_id TEXT,
      entity_type TEXT NOT NULL,
      sync_trigger TEXT,
      started_at TEXT NOT NULL,
      completed_at TEXT,
      status TEXT NOT NULL DEFAULT 'running',
      records_processed INTEGER NOT NULL DEFAULT 0,
      records_created INTEGER NOT NULL DEFAULT 0,
      records_updated INTEGER NOT NULL DEFAULT 0,
      error_message TEXT
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_sync_logs_started ON meta_sync_logs(started_at)',

    `CREATE TABLE IF NOT EXISTS meta_action_logs (
      id ${id},
      user_id INTEGER,
      username TEXT,
      source TEXT,
      action TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      entity_name TEXT,
      old_value TEXT,
      new_value TEXT,
      status TEXT NOT NULL,
      error_message TEXT,
      created_at ${ts}
    )`,
    'CREATE INDEX IF NOT EXISTS idx_meta_action_logs_created ON meta_action_logs(created_at)',

    // Thresholds for the Winning / Needs attention flags. scope_type is
    // organization | ad_account | page | campaign; the organization row has
    // scope_id ''. Nulls mean "no threshold".
    `CREATE TABLE IF NOT EXISTS meta_targets (
      id ${id},
      scope_type TEXT NOT NULL DEFAULT 'organization',
      scope_id TEXT NOT NULL DEFAULT '',
      target_roas ${num},
      target_actual_roas ${num},
      max_cpa ${num},
      max_cpm ${num},
      min_ctr ${num},
      max_rts ${num},
      updated_by INTEGER,
      updated_at ${ts}
    )`,
    'CREATE UNIQUE INDEX IF NOT EXISTS idx_meta_targets_scope ON meta_targets(scope_type, scope_id)',

  ];
}

async function ensureMetaAdsSchema(db) {
  for (const sql of metaAdsStatements(db)) {
    await db.exec(sql);
  }
  // Profitability joins POS orders to ads by Pancake's stored Facebook ad id.
  // Only a speed-up, so it must never block boot: on an old SQLite file the
  // pos_orders rebuild migration can leave ad_id missing until the next start.
  try {
    await db.exec('CREATE INDEX IF NOT EXISTS idx_pos_orders_ad_id ON pos_orders(ad_id)');
  } catch (error) {
    console.warn(`[meta_ads] skipped idx_pos_orders_ad_id: ${error.message}`);
  }
}

module.exports = { ensureMetaAdsSchema, metaAdsStatements };
